# Generated by Django 4.1 on 2022-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=False, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
