# Generated by Django 4.1.1 on 2022-09-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
